### ISSUE TITLE
Doesn't work - Cannot read property 'ref' of null - Codesandbox example has same problem

### ISSUE THREAD

**Issue by clintjansen** [tim-soft/react-spring-lightbox#16]
Getting cannot read property 'ref' of null from @react-spring on useTransition 

Codesandbox example has same problem
https://codesandbox.io/s/71hts

**Comment by tim-soft** [comment]
@clintjansen thanks for reporting this, I'll take a look sometime this week

**Comment by tim-soft** [comment]
Fixed in v1.4.11, codesandbox is updated
