### ISSUE TITLE
Feature Request - lazyloading images

### ISSUE THREAD

**Issue by hans2103** [tim-soft/react-spring-lightbox#3]
Thank you for your great flexible image gallery lightbox with native-feeling touch gestures and buttery smooth animations, built with react-spring.
It would be very useful if you can builtin lazyloading images too.

**Comment by tim-soft** [comment]
What kind of api would you propose for lazy loading images?

**Comment by hans2103** [comment]
@tim-soft 
I would like to propose two API

# 1. native support
I would like to propose to implement the native attribute `loading="lazy"`
I am aware that not all browsers will support this at the moment.
https://caniuse.com/#search=lazy

# 2. with a fallback to other browsers that do not support lazy-loading
https://web.dev/native-lazy-loading/

**Comment by kmvan** [comment]
Good idea.

**Comment by tim-soft** [comment]
Lazy loading via `<img loading="lazy"` is out now in 1.5.0

you can now pass any valid `<img />` attribute in the `images` array
