### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by buffaloDeveloper** [tim-soft/react-spring-lightbox#31]
Failed to compile.
/Users/xxx/workspace/xxx/xxx-test-app/node_modules/xxx-ui-components/node_modules/react-spring-lightbox/dist/index.es.js
Module not found: Can't resolve 'styled-components' in '/Users/xxx/workspace/xxx/xxx-test-app/node_modules/xxx-ui-components/node_modules/react-spring-lightbox/dist'

**Comment by joeyfigaro** [comment]
was this resolved on your end? seems to still be an issue.
