### ISSUE TITLE
Feature Request - video in lightbox

### ISSUE THREAD

**Issue by hans2103** [tim-soft/react-spring-lightbox#5]
It would be cool and useful if your lightbox solution can show video elements too:

current const images:
```
const images = [
    {
        src:
            'https://timellenberger.com/static/blog-content/dark-mode/win10-dark-mode.jpg',
        alt: 'Windows 10 Dark Mode Setting'
    },
```

possible new solution const images:
```
const images = [
    {
        src:
            'https://timellenberger.com/static/blog-content/dark-mode/win10-dark-mode.jpg',
        alt: 'Windows 10 Dark Mode Setting,
        type: 'video,
        video: 'path-to-video.mp4'
    },
```

what do you think of this feature request?

**Comment by tim-soft** [comment]
I think what might make more sense is being able to pass in your own custom components for where the image would go, then you can do whatever you want without any restrictions by the library itself

**Comment by AlesSrsen** [comment]
> I think what might make more sense is passing in your own custom components where the image would go, then you can do whatever you want without any restrictions by the library, which has been the philosophy so far

How would you go about doing that? Only workaround I've found was to use ImageOverlay as the component to display video...

**Comment by bhavishya2107** [comment]
Did you find any solution for this ? @tim-soft  @AlesSrsen 
I tried embedding `react-player` based on file type but it still loads the video file as image and shows a broken image.

**Comment by AlesSrsen** [comment]
I think I managed to use this library by creating <Video> component which I overlayed over the image the lightbox shows using [renderImageOverlay](https://github.com/tim-soft/react-spring-lightbox#props) prop.
